################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
intro2cpp/Season1FinalTest/WhichCtor \
intro2cpp/Unit01/Alohaworld \
intro2cpp/Unit01/Alohaworld1 \
intro2cpp/Unit02/TestAnimation1 \
intro2cpp/Unit02/TestAnimation2 \
intro2cpp/Unit02/TestInput \
intro2cpp/Unit02/TestProject \
intro2cpp/Unit02/consoleEgeTest \
intro2cpp/Unit02/egeTest \
intro2cpp/Unit02/winApp \
intro2cpp/Unit02/测试项目 \
intro2cpp/Unit03/AmbiguousOverloading \
intro2cpp/Unit03/DefaultArgument-Overloading \
intro2cpp/Unit03/DefaultArgumentDemo \
intro2cpp/Unit03/InlineDemo \
intro2cpp/Unit03/InlineDemo1 \
intro2cpp/Unit03/InlineDemo2 \
intro2cpp/Unit03/TestFunctionOverloading \
intro2cpp/Unit03/TestPassByReference \
intro2cpp/Unit03/TestReferenceVariable \
intro2cpp/Unit03/VarInNestingBlock \
intro2cpp/Unit03/boolType \
intro2cpp/Unit03/ooVarInit \
intro2cpp/Unit03/referenceToPointer \
intro2cpp/Unit04/AlohaWorld \
intro2cpp/Unit04/AnonymousObject \
intro2cpp/Unit04/Circle3 \
intro2cpp/Unit04/CompareString \
intro2cpp/Unit04/DefaultConstructor1 \
intro2cpp/Unit04/DefaultConstructor2 \
intro2cpp/Unit04/HideDataField \
intro2cpp/Unit04/PassObjectByReference \
intro2cpp/Unit04/PassObjectByValue \
intro2cpp/Unit04/PassObjectToPointer \
intro2cpp/Unit04/String \
intro2cpp/Unit04/TestCircle \
intro2cpp/Unit04/TestCircle2 \
intro2cpp/Unit04/TestCircleWithDeclaration \
intro2cpp/Unit04/TestCopyCtor \
intro2cpp/Unit04/TotalArea \
intro2cpp/Unit05/CopyConstructorDemo \
intro2cpp/Unit05/CustomCopyConstructor \
intro2cpp/Unit05/ShallowCopyDemo \
intro2cpp/Unit05/TestCircle5 \
intro2cpp/Unit05/TestCircle6 \
intro2cpp/Unit05/TestCourse \
intro2cpp/Unit05/TestFriendClass \
intro2cpp/Unit05/TestFriendFunction \
intro2cpp/Unit05/TestPerson \
intro2cpp/Unit05/TestPerson1 \
intro2cpp/Unit05/TestStackOfIntegers \
intro2cpp/Unit05/TestVector \
intro2cpp/Unit05/VectorInVector \
intro2cpp/Unit06/ChainingDemo \
intro2cpp/Unit06/DynamicCastingDemo \
intro2cpp/Unit06/PolymorphismDemo \
intro2cpp/Unit06/TestFruit \
intro2cpp/Unit06/TestGeometricObject \
intro2cpp/Unit06/TestGeometricObject2 \
intro2cpp/Unit06/VisibilityDemo \
intro2cpp/Unit06/WhyPolymorphismDemo \
intro2cpp/Unit07/AppendFile \
intro2cpp/Unit07/BinaryArrayIO \
intro2cpp/Unit07/BinaryCharOutput \
intro2cpp/Unit07/BinaryIntOutput \
intro2cpp/Unit07/BinaryWrite \
intro2cpp/Unit07/BufferedCin \
intro2cpp/Unit07/BufferedCout \
intro2cpp/Unit07/CopyFile \
intro2cpp/Unit07/FilePointer/TellpAndTellg \
intro2cpp/Unit07/RandomAccessFile \
intro2cpp/Unit07/ReadCity \
intro2cpp/Unit07/SetPrecision/Debug \
intro2cpp/Unit07/SetPrecision \
intro2cpp/Unit07/ShowStreamState \
intro2cpp/Unit07/TestEndOfFile \
intro2cpp/Unit07/TextFileInput \
intro2cpp/Unit07/TextFileOutput \
intro2cpp/Unit07/WriteFormatData \
intro2cpp/Unit07/flush \
intro2cpp/Unit08/DefaultAssignmentDemo \
intro2cpp/Unit08/StringPlus \
intro2cpp/Unit08/TestNewRationalClass \
intro2cpp/Unit08/TestRationalClass \
intro2cpp/Unit09/ExceptionDemo1 \
intro2cpp/Unit09/ExceptionDemo2 \
intro2cpp/Unit09/ExceptionDemo3 \
intro2cpp/Unit09/MultipleCatchDemo \
intro2cpp/Unit09/Quotient \
intro2cpp/Unit09/QuotientWithException \
intro2cpp/Unit09/QuotientWithFunction \
intro2cpp/Unit09/QuotientWithIf \
intro2cpp/Unit09/RethrowExceptionDemo \
intro2cpp/Unit09/ThrowAndDtor \
intro2cpp/Unit09/TriangleException \
intro2cpp/Unit10/GenericMaxValue \
intro2cpp/Unit10/GenericSort \
intro2cpp/Unit10/InstantiationClass \
intro2cpp/Unit10/InstantiationFunction \
intro2cpp/Unit10/MultipleTemplateParameters \
intro2cpp/Unit10/SelectionSort \
intro2cpp/Unit10/TestGenericStack \
intro2cpp/Unit11/DequeDemo \
intro2cpp/Unit11/IteratorDemo \
intro2cpp/Unit11/IteratorOperatorDemo \
intro2cpp/Unit11/ListDemo \
intro2cpp/Unit11/MapDemo \
intro2cpp/Unit11/PriorityQueueDemo \
intro2cpp/Unit11/QueueDemo \
intro2cpp/Unit11/SetDemo \
intro2cpp/Unit11/SimpleSTLDemo \
intro2cpp/Unit11/StackDemo \
intro2cpp/Unit11/VectorDemo \
intro2cpp/backup/demo/src \
intro2cpp/backup/man/netfriendsdemo \
intro2cpp/backup/man/tutorial \
intro2cpp/backup/src \
intro2cpp/backup/src/demo \
intro2cpp/backup/src/graphics10/Release \
intro2cpp/backup/src/graphicstest \
intro2cpp/backup/src/lpng \
intro2cpp/backup/src/tools \
intro2cpp/backup/src/tutorial \
intro2cpp/dist \
intro2cpp/exe \
intro2cpp/temp \
intro2cpp/temp/vsTest/vsTest/Debug \
intro2cpp/temp/vsTest/vsTest \
intro2cpp \

